#File destination path

[file_dest]
jn_fm = 'C:\Users\Dell\IdeaProjects\TaoSJDL\src\TaoSJ Data\JN\FM'
jn_sc = 'C:\Users\Dell\IdeaProjects\TaoSJDL\src\TaoSJ Data\JN\SC'
bhyx_fm = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\BHYX\FM'
dsby_ab = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\DSBY\AB'
gz_fm = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\GZ\FM'
ljy_sc = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\LJY\SC'
swc_sc = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\SWC\SC'
xhd_sc = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\XHD\SC'
xq_sc = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\XQ\SC'
xqsc_sc ='C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\XQSC\SC'
yjx_fm = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\YJX\FM'
yyx_bn = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\YYX\BN'
yyx_fm = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\YYX\FM'
yzw_bn = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\YZW\BN'
zdyw_bn = 'C:\Users\Dell\IdeaProjects\tf-es-dumping\TaoSJ Data\ZDYW\BN'