#File destination path

[file_dest]
jn_fm = '\src\TaoSJ Data\JN\FM'
jn_sc = '\src\TaoSJ Data\JN\SC'
bhyx_fm = '\src\TaoSJ Data\BHYX\FM'
dsby_ab = '\src\TaoSJ Data\DSBY\AB'
gz_fm = '\src\TaoSJ Data\GZ\FM'
ljy_sc = '\src\TaoSJ Data\LJY\SC'
swc_sc = '\src\TaoSJ Data\SWC\SC'
xhd_sc = '\src\TaoSJ Data\XHD\SC'
xq_sc = '\src\TaoSJ Data\XQ\SC'
xqsc_sc ='\src\TaoSJ Data\XQSC\SC'
yjx_fm = '\src\TaoSJ Data\YJX\FM'
yyx_bn = '\src\TaoSJ Data\YYX\BN'
yyx_fm = '\src\TaoSJ Data\YYX\FM'
yzw_bn = '\src\TaoSJ Data\YZW\BN'
zdyw_bn = '\src\TaoSJ Data\ZDYW\BN'
dsyp_sc = '\src\TaoSJ Data\DSYP\SC'
jz_fm = '\src\TaoSJ Data\JZ\FM'


[defined_vars]
taosj_phone_num = '91784364'
taosj_pw = 'fupin123'
login_url = 'https://login.taosj.com/?redirectURL=https%3A%2F%2Fwww.taosj.com%2F'
taosj_meta_data = 'C:\Users\aujh1\IdeaProjects\TaoSJDL\src\TaoSJ Meta'
download_dump_folder = '\download-dump'
